### ISSUE TITLE
coveralls problem with non-UTF-8 character from external library

### ISSUE THREAD

**Issue by rtp-calpoly** [z4r/python-coveralls#31]
I am running my test coverage assessment through Django Nose, using the following option (@settings.py):

    NOSE_ARGS = [
        '--verbosity=3',
        '--cover-package=services.accounts,services.common,'
        'services.communications,services.configuration,services.leop,'
        'services.network,services.scheduling,services.simulation'
    ]

As you can see, I am restricting the assessment of the coverage only to the packages that I develop by myself. The sequence of commands that I use in order to execute this assessment is the following:

    coverarge erase
    coverage run manage.py test
    coveralls

When invoking "coveralls", it tries to run the coverage assessment also over the external libraries, so that I get the following exception when it tries to access to the source code for "datetime":

    >>> filename = /home/rtubio/repositories/satnet/server/development_3k/.venv/lib/python3.4/site-packages/dateutil/parser.py
    Traceback (most recent call last):
      File "/home/rtubio/repositories/satnet/server/development_3k/.venv/bin/coveralls", line 11, in <module>
        sys.exit(wear())
      File "/home/rtubio/repositories/satnet/server/development_3k/.venv/lib/python3.4/site-packages/coveralls/__init__.py", line 91, in wear
        source_files=coverage.coveralls(args.base_dir, ignore_errors=args.ignore_errors, merge_file=args.merge_file),
      File "/home/rtubio/repositories/satnet/server/development_3k/.venv/lib/python3.4/site-packages/coveralls/control.py", line 9, in coveralls
        return reporter.report(base_dir, ignore_errors=ignore_errors, merge_file=merge_file)
      File "/home/rtubio/repositories/satnet/server/development_3k/.venv/lib/python3.4/site-packages/coveralls/report.py", line 14, in report
        source = fp.readlines()
      File "/home/rtubio/repositories/satnet/server/development_3k/.venv/lib/python3.4/codecs.py", line 313, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 1130: invalid continuation byte

The first line (>>> filename = 'XXXX') was manually added by my to "coveralls/report.py:12", since the original exception does not report the name of the file that provokes the exception to be thrown (following the recommendation from https://github.com/eddyxu/cpp-coveralls/issues/24). In that very same issue, they suggest the usage of '--exclude', an option that seems to be available for "cpp-coveralls" but not for "python-coveralls".

Therefore, the following questions arise:

1) Is the coverage tool ignoring the option for django-nose in which I specify the package over which to assess the coverage?
2) Is there anyway in which I can tell "coveralls" to ignore certain packages?

Thanks for the help in advance.

**Comment by z4r** [comment]
Could you read #30?

**Comment by rtp-calpoly** [comment]
Thank you so much @z4r , I did not read that issue. I included the ".coveragerc" and now it is working.
